// Generates src/plugin/generated-catalog.ts from models.json (single source
// of truth) so the compiled plugin carries the catalog without runtime file
// reads. Run as part of `npm run build` (see package.json) before tsc/tsdown.
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const models = JSON.parse(readFileSync(resolve(root, 'models.json'), 'utf8'))

const rows = models.map((m) => {
  const name = m.name || ''
  const windowSec = /whisper/i.test(name) ? 30 : 25
  const streaming = /stream|realtime|voxtral/i.test(name) ? 1 : 0
  return `  ${JSON.stringify({
    id: m.id,
    name: m.name,
    repo: m.repo,
    file: m.file,
    size: Number(m.size) || 0,
    recommended: m.recommended === true,
    windowSec,
    streaming: streaming === 1,
  })},`
}).join('\n')

const out = `// Generated by scripts/gen-catalog.mjs from models.json — do not edit by hand.
export interface CatalogEntry {
  id: string
  name: string
  repo: string
  file: string
  size: number
  recommended: boolean
  windowSec: number
  streaming: boolean
}

export const CATALOG: readonly CatalogEntry[] = [
${rows}
]
`

writeFileSync(resolve(root, 'src/plugin/generated-catalog.ts'), out)
console.log(`generated src/plugin/generated-catalog.ts (${models.length} models)`)
